name: ML Platform Python SDK CI
trigger:
  change:
    types:
      - create
      - push
jobs:
  python_static_analysis_and_unit_test:
    name: Python CodeStyle & Unit Test
    image: hub.byted.org/codebase/ci_python_37:latest
    steps:
      - commands:
          # Environment setup
          - apt-get update && apt-get install -y build-essential libsnappy-dev
          - pip install pre-commit
          - pre-commit run --all-files
          # Unit test starts here
          - echo "start unit test"
          - pip3 install -r requirements.txt
          - bash -ex scripts/py_unit_test.sh
