# Get Started with Codebase CI https://bytedance.feishu.cn/wiki/wikcnclt1VL6j2z0I0fFE6cdzwc
name: SDK Operator CI
trigger:
  change:
    types:
      - create
      - push
jobs:
  python_static_analysis_and_unit_test:
    name: Python Static Analysis & Unit Test
    image: hub.byted.org/codebase/ci_python_37:latest
    steps:
      - commands:
          # Environment setup
          - apt-get update && apt-get install -y build-essential libsnappy-dev
          - pip3 install -i https://bytedpypi.byted.org/simple -r requirements.txt

          # Unit test starts here
          - bash -ex scripts/py_unit_test.sh
